name: vote_your_face
description: "Vote your face app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.6.8
  auto_route: ^8.0.3
  equatable: ^2.0.5
  formz: ^0.7.0
  amplify_authenticator: ^1.5.5
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  vote_circle_repository:
    path: packages/vote_circle_repository
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/placeholder/
    - assets/svg/
