name: vote_your_face
description: "Vote your face app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0
  auto_route: ^8.2.0
  equatable: ^2.0.5
  formz: ^0.7.0
  amplify_authenticator: ^2.0.1
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  vote_circle_repository:
    path: packages/vote_circle_repository
  rankings_repository:
    path: packages/rankings_repository
  flutter_svg: ^2.0.10+1
  bloc_concurrency: ^0.2.5
  logger: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/placeholder/
    - assets/svg/
