name: vote_circle_api
description: "Vote circle api."
version: 0.0.1
homepage: ''
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  http: ^1.2.1
  json_annotation: ^4.8.1
  authentication_repository:
    path: ../authentication_repository
  logger: ^2.2.0

dev_dependencies:
  coverage: ^1.7.2
  build_runner: ^2.4.9
  test: ^1.25.2
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.2
